### ISSUE TITLE
sbt plugin for Scala codegen

### ISSUE THREAD

**Issue by raboof** [lightbend/akkaserverless-java-sdk#379]
following the same approach as in Akka gRPC: bringing in sbt-protoc transitively and registering the codegen (for now a dummy) as a protoc generator:

* [x] sbt-protoc integration #390
* [x] pass proto definitions into 'model' for generation #390
* [x] separate protoc generators for both 'compile' and 'test' scope #390
* [x] create an sbt task for generating the code that the users will then maintain themselves. In the default project template we'll make a dependency between the 'compile' task and this task so the user won't have to worry about this at first, but can disable it when it gets in the way later.
