### ISSUE TITLE
Replace reflection with generated code

### ISSUE THREAD

**Issue by patriknw** [lightbend/akkaserverless-java-sdk#52]
Since the codegen is the selected approach we should remove the Java annotation based alternative and its reflection based implementation.

* [x] Value Entities: Effect API (no implementation) #62
* [x] Value Entities: Implementation of Effect API #91
* [x] Value Entities: Update codegen to produce Effect-based interface, initial implementation and tests #120
* [x] Value Entities: 'manual' prototype of 'handler' code to replace reflection-based implementation #73
* [x] Value Entities: Update codegen to produce 'handler' code to replace reflection-based implementation #148 and #243
* [x] Event Sourced Entities: Effect API (no implementation) #62 
* [x] Event Sourced Entities: Implementation of Effect API https://github.com/lightbend/akkaserverless-java-sdk/pull/91
* [x] Event Sourced Entities: Update codegen to produce Effect-based interface, initial implementation and tests https://github.com/lightbend/akkaserverless-java-sdk/pull/132
* [x] Event Sourced Entities: Update codegen to produce 'handler' code to replace reflection-based implementation #163 (potential additional cleanup in #150), actual codegen of handler in #231
* [x] Views: Effect API (no implementation) #230
* [x] Views: Implementation of Effect API #240
* [x] Views: Update codegen to produce Effect-based interface, initial implementation and tests #240
* [x] Views: Update codegen to produce 'handler' code to replace reflection-based implementation #240
* [x] Actions: Effect API (no implementation) #258 
* [x] Actions: Implementation of Effect API #258 
* [x] Actions: Update codegen to produce Effect-based interface, initial implementation and tests #258 
* [x] Actions: Update codegen to produce 'handler' code to replace reflection-based implementation #258 
* [x] Protobuf option to support JSON API's that convert to method calls with Jackson-serialized objects
* [x] Remove annotation-based implementation
* [x] Re-enable all tests/samples/CI

**Comment by raboof** [comment]
The goal here is to simplify things by having 'one way' to do things, and since via the 'codegen' we already have all the information on where things go, the annotations are not really needed anymore. So we want to replace the `AkkaServerless().registerXxx().registerYyy().start()` with something that is generated as part of the codegen and has the same effect, but without relying on the annotations.

The general approach to taking this on could be:
* Take #62 as the starting point
* Start converting the java-customer-registry sample, replacing `AkkaServerless().registerXxx().registerYyy().start()` with a hand-written version of the to-be-generated code
* When that works out, by that time the codegen has been merged to this repo as well (#61), and we can rebase and adapt the codegen to generate that code rather than hand-writing it

**Comment by patriknw** [comment]
Steps look like a good approach.

I haven't looked at any details of how to do this, but somewhere there is some glue between the incoming grpc requests and corresponding command handlers. Today that's done by matching on the command handler names (command handler annotation names). That glue could be generated somehow. In the end, removing all annotations and reflection support.

**Comment by raboof** [comment]
Right now, we are using reflection to find out what information a method needs: for example, for a value entity, we may pass in the command, the (optional) current state and the context, depending on what parameters are present on the command handler method.

Do we want to change this to always pass in all 3? Or do we want to keep using reflection for that aspect?
