### ISSUE TITLE
[epic] New codegen annotation

### ISSUE THREAD

**Issue by octonato** [lightbend/akkaserverless-java-sdk#724]
TODO: 

- [x] add new annotations in SDK project #716. Can be moved to framework repo eventually, see https://github.com/lightbend/akkaserverless-framework/pull/970
- [x] modify all compile tests to use new annotations - #739
- [x] adapt documentation - #748
- [ ] adapt TCK tests in the SDK - see #789
- [x] adapt quickstarts - impacts main documentation -#756 and https://github.com/lightbend/akkaserverless-docs/pull/1124
- [x] include some new compile tests to exercise package lookup functionality. See design description below. Done in #777, #778, #780, #774, #776
- [ ] all the above but for the javascript SDK (we can create the epic once we finish this one) 

### Short Description

This description summarizes the design that have been discusses in https://github.com/lightbend/akkaserverless-framework/issues/898 and https://github.com/lightbend/akkaserverless/discussions/4097#discussioncomment-788413. 

The goal is to reduce the moving parts on the annotations that are used by the codegen. 

The current implementation requires two different annotations that need to be added in two different files and then glued back together through a `component` field. 

For example, in `counter_domain.proto`, as user will have to add the following annotation at file level: 

```proto
option (akkaserverless.file).event_sourced_entity = {
    name: "Counter" // <- this is the name of entity class
    entity_type: "counter" 
    state: "CounterState" // internal domain state
    events: ["ValueIncreased"] // will generate event handlers for types declared here
};
```

then in the service proto, they will have to add: 

```proto
service CounterService {
    option (akkaserverless.service) = {
        type : SERVICE_TYPE_ENTITY // <- somehow repetitive, we already said it's an event_sourced_entity
        component: ".Counter" // <- also repetitive, we already declared it will be Counter
    };
	...
}
```

The component field above makes the link between the two and the codegen will use these two annotations to generated all the Java/Scala classes. 

The proposal is to replace the annotations one single annotation to be added to the Service definition.

```proto
service CounterService {
    option (akkaserverless.codegen) = {
       event_sourced_entity: {
			name: "Counter"
            package_name: "com.example.domain"
            entity_type: "counter" 
            state: "CounterState"
            events: ["ValueIncreased"]
		}
    };
	...
}
```

With this single annotation we can generate the same Java/Scala classes. 

The entity class will be generated with the fully qualified name `com.example.domain.Counter`, while the proto messages `CounterState` and `ValueIncreased` can be define in any proto file, but it is required that they are in the proto pacakge `com.example.domain`.

Alternatively, one could have them in different places by using prefixes in the messages name, for example: 

```proto
service CounterService {
    option (akkaserverless.codegen) = {
       event_sourced_entity: {
			name: "Counter"
            package_name: "com.example.domain"
            entity_type: "counter" 
            state: "state.CounterState"
            events: ["events.ValueIncreased"]
		}
    };
	...
}
```

Resulting in entity class `com.example.domain.Counter`, state `com.example.domain.state.CounterState` and event `com.example.domain.events.ValueIncreased`.
